// CODE GENERATED BY GOOGLE GEMINI
`timescale 1ns / 1ps

module alu_tb;
  // Using 8 bits to keep it simple, just like your previous testbenches
  parameter WIDTH = 8; 

  reg [WIDTH-1:0] x, y;
  reg [3:0] opcode;
  wire [WIDTH-1:0] result;
  wire zero, cout, overflow;

  // Instantiate the ALU module
  alu #(.WIDTH(WIDTH)) dut (
      .x(x),
      .y(y),
      .opcode(opcode),
      .result(result),
      .zero(zero),
      .cout(cout),
      .overflow(overflow)
  );

  initial begin
    $display("--- Starting ALU Integration Tests ---");

    // Test ADD (0000)
    x = 8'd10; y = 8'd15; opcode = 4'b0000; #10;
    if (result !== 8'd25) $display("FAIL: ADD routed incorrectly!");
    else $display("PASS: ADD");

    // Test SUB (0001)
    x = 8'd20; y = 8'd5; opcode = 4'b0001; #10;
    if (result !== 8'd15) $display("FAIL: SUB routed incorrectly!");
    else $display("PASS: SUB");

    // Test AND (0010)
    x = 8'b10101010; y = 8'b11110000; opcode = 4'b0010; #10;
    if (result !== 8'b10100000) $display("FAIL: AND routed incorrectly!");
    else $display("PASS: AND");

    // Test SLL (1000)
    x = 8'b00000001; y = 8'd3; opcode = 4'b1000; #10;
    if (result !== 8'b00001000) $display("FAIL: SLL routed incorrectly!");
    else $display("PASS: SLL");

    $display("--- ALU Tests Completed ---");
    $finish;
  end
endmodule

